### ISSUE TITLE
can't create project of archetype 14

### ISSUE THREAD

**Issue by lgc0313** [Adobe-Marketing-Cloud/aem-project-archetype#123] opened 2018-08-24 06:01 UTC
when I ran the commond, an error occurred
`mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate \
 -DarchetypeGroupId=com.adobe.granite.archetypes \
 -DarchetypeArtifactId=aem-project-archetype \
 -DarchetypeVersion=14 \
 -DarchetypeCatalog=https://repo.adobe.com/nexus/content/groups/public/`

![jietu20180824-135802](https://user-images.githubusercontent.com/3353386/44567675-1f84b280-a7a6-11e8-8eb9-a7d8160f80fa.jpg)

**Comment by toniedzwiedz** [comment] 2018-08-26 20:34
@lgc0313 I can't reproduce this behaviour at the moment. The log says that Maven was unable to locate version 14 of the archetype in Adobe's public Nexus, which is strange as it's been there since Aug 2nd.

I did experience some downtime of Adobe's public nexus last week, even got HTTP 500 responses. Perhaps you were unlucky enough to try it when the repository was down and the artefact never got downloaded?

Does the same thing happen if you just try again now?

**Comment by gabrielwalt** [comment] 2018-09-13 16:37
Thanks @lgc0313, I think that this happened because of an outage of repo.adobe.com.
I'm closing this as of now, but please reopen it in case the issue still occurs.

**Closed by gabrielwalt** 2018-09-13 16:37 UTC
