### ISSUE TITLE
Just doesn't work.....

### ISSUE THREAD

**Issue by kkedem** [Adobe-Marketing-Cloud/aem-project-archetype#95] opened 2017-06-13 12:10 UTC
Spent couple of hours on getting a project up.. This tool just doesn't work... Tried both ways using the eclipse tool and the mvn command, none works..

![snip20170613_5](https://user-images.githubusercontent.com/6771373/27081727-9978a9b8-5039-11e7-934f-9abb54c82ce0.png)

Here is my machine config - 

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.5", arch: "x86_64", family: "mac"

**Comment by jamiecounsell** [comment] 2017-06-14 14:52
@kkedem can you post the error details from the maven command with the `-e` switch? Also, did you set up your maven `settings.xml` as described in [this article](https://helpx.adobe.com/experience-manager/using/first-osgi.html)? I had some issues building it the other day before configuring my settings.

**Comment by gopackgo90** [comment] 2017-06-20 03:33
I am having the exact same issue. It's not an issue with the project building with maven. It is a problem opening the project in Eclipse. To reproduce, simply attempt to make a new maven project using archetype 11 in Eclipse or from the maven commands and attempt to import the maven project into eclipse. If you look at the error log (About Eclipse -> Installation Details -> Configuration tab -> View Error Log, you will see a stack trace similar to this: https://github.com/tesla/m2eclipse-tycho/issues/4#issue-2036135

I too have spent hours trying to get this to work, but nothing's working.

**Comment by danielrndm** [comment] 2017-06-26 19:48
Are you guys planning on fixing this? I'm also facing this problem.

My setup is:
Windows 10
Eclipse Neon
AEM 6.3
Java 1.8
Maven 3.5.0

Previous versions of the archetype don't seem to work as I assume they need java 7. The newest archetype 12 doesn't work either.

**Comment by gopackgo90** [comment] 2017-06-26 23:25
This seems to be fixed by https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/commit/919d98e582583e1b5bf1676963ab39fa558f8354 . I was able to remove the executions element, delete any Eclipse project related files, and open in a new workspace without any further issues.

**Comment by kkedem** [comment] 2017-06-29 13:41
I can confirm that this is fixed by doing what @gopackgo90 has described.

**Comment by danielrndm** [comment] 2017-06-29 14:09
true.. Just got rid of the executions element and now it compiles fine. 

thanks a bunch @gopackgo90

**Closed** 2017-08-17 19:55 UTC
Labels: question
