### ISSUE TITLE
add mode="merge" to ui.content filter.xml

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Marketing-Cloud/aem-project-archetype#127] opened 2018-10-17 16:07 UTC
In the [WKND Tutorial](https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-wknd-tutorial-develop/part1.html) there is a step to add `mode="merge"` to the `filter.xml` in the `ui.content` module.

This ideally should be done by the archetype itself, not required to be done manually.

After doing this and releasing, the WKND tutorial should probably be updated to reflect that this step is no longer necessary.

/cc @godanny86 @davidjgonzalez

**Comment by godanny86** [comment] 2018-10-17 16:11
This is a duplicate of: https://github.com/Adobe-Marketing-Cloud/aem-project-archetype/issues/113 (which has been closed). It looks like it will be fixed in archetype 15...

**Comment by justinedelson** [comment] 2018-10-17 16:16
I don't think so @godanny86. #113 is about the merge_preserve setting in the pom whereas this one is about the filter.xml. But they both relate to the same step in the tutorial :)

**Comment by godanny86** [comment] 2018-10-17 16:18
Ah yes you are correct @justinedelson , not enough coffee this morning I guess : )

**Comment by andreeadracea** [comment] 2018-10-25 07:54
@justinedelson, thank you for bringing up this improvement.
I've created an internal issue for it. (CQ-4256008)

**Closed** 2018-10-25 09:47 UTC

**Comment by bpauli** [comment] 2018-10-25 09:54
@godanny86 I just released a new version of the archetype which contains the fix of this issue. Can you please update the WKDT Tutorial accordingly?

**Comment by bpauli** [comment] 2018-10-25 09:54
Btw. @justinedelson thank you for bringing this up!

**Comment by godanny86** [comment] 2018-10-25 12:49
Will do @bpauli. We are planning an update soon with the latest version of core components, will roll this change into it.
